In [1]:
import numpy as np

In [7]:
a = np.array([[1 , 2, 3 ,4 ,5, 6] , [2, 3, 4 , 6, 8 , 9]])
print(a)
print(type(a))

[[1 2 3 4 5 6]
 [2 3 4 6 8 9]]
<class 'numpy.ndarray'>


In [11]:

c = np.array([
    [[1, 2], [3, 4], [5, 6]],
    [[7, 8], [9, 10], [11, 12]]
])

print(c)
print(c.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [ ]:
#flatten vs ravel

In [18]:
a = np.array([10 , 20  , 30 , 40])
b = np.array([1 , 2 ,3, 4])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a**b)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[0 0 0 0]
[     10     400   27000 2560000]


In [21]:
# Slicing 
a = np.array([10 , 20 , 30 , 40 , 50])
print(a[1:4])
print(a[:3])
print(a[::-1])

[20 30 40]
[10 20 30]
[50 40 30 20 10]


In [24]:
a = np.array([10 , 15 , 20 , 25])
print(a)
mask = a>18
print(mask)
print(a[mask])
print(a>18)

[10 15 20 25]
[False False  True  True]
[20 25]
[False False  True  True]


In [32]:
a = np.array([1 , 2,3, 45, 6, 7, 7 , 8, 89 , 98 , 987])
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.max(a))

1253
113.9090909090909
7.0
987


In [41]:
a = np.array([1 , 2, 3 ])
b = np.array([1 , 3 ,5 ])
print(np.concatenate([a , b]))

[1 2 3 1 3 5]


In [47]:
a = np.array([1 , 2, 3  ,1 ,23 ,4,56  ,54, 54, 67, 54, 45 ,768, 87, 56 ,0 , 0 , 0 ,0 , 9, 56])
print(np.unique(a))

[  0   1   2   3   4   9  23  45  54  56  67  87 768]
